name: "Backend unit tests"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Set up Python"
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    
    - name: "Install dependencies"
      run: |
        cd ./backend
        pip install -r requirements.txt

    - name: "Unit tests: Parser"
      run: |
        cd ./backend
        python -m pytest ./demodata_parser/

    - name: "Unit tests: Server"
      run: |
        cd ./backend
        python -m pytest ./demodata_server/